spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    database: postgresql
    show-sql: true
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/